In [1]:
number=15

In [2]:
type(number)

int

In [3]:
my_list=[1,2,3]


In [5]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

### Numpy

In [ ]:
#pip install numpy
#pip3 install numpy

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
array_a=np.array([1,2,3,4])

In [10]:
array_b= np.array([0,1,1.5,2])

In [11]:
array_b

array([0. , 1. , 1.5, 2. ])

In [12]:
array_a[0]

1

In [13]:
array_b[-1]

2.0

In [14]:
array_a[:2]

array([1, 2])

In [15]:
array_a.dtype
#buna limit verebiliriz

dtype('int64')

In [16]:
array_b.dtype

dtype('float64')

In [17]:
empty_array=np.array([])

In [18]:
empty_array.dtype

dtype('float64')

In [20]:
np.array([1,2,3,4], dtype=np.float_)
#floata çevirme

array([1., 2., 3., 4.])

In [21]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
#numpy boyutları sabit olarak tutar.İşlemlerde sabit yük verir.
#Pythonda veri büyüdükçe işlemde büyür.

In [23]:
array_c=np.array(["ada","lovelace"])

In [24]:
array_c.dtype

dtype('<U8')

### Dİmensions and shapes

In [ ]:
#matriks oluşturmaya izin verir

In [25]:
my_array=np.array([
    [1,2,3],
    [4,5,6]
])

In [26]:
array_a.shape

(4,)

In [28]:
my_array.shape
#2 satır 3 sütun olarak bilgi verir

(2, 3)

In [29]:
#dimension
array_a.ndim

1

In [30]:
my_array.ndim

2

In [31]:
my_array.size
#size her bir değerden kaç tane olduğunu verir


6

In [33]:
my_array=np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
         [6,5,6],
         [3,2,1]
    ]
])

In [34]:
my_array.ndim

3

In [35]:
my_array.shape

(2, 2, 3)

In [36]:
my_array.size

12

In [37]:
#matrixlerin boyutları tutarlı olması lazım


### İndexing and slicing

In [38]:
my_array=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [39]:
my_array[1]
#1. row

array([4, 5, 6])

In [40]:
my_array[1][0]
#1.satırın 1.elemanı

4

In [41]:
my_array[1,0]

4

In [42]:
my_array[0:2]
#önce rowlar üzerinde çalışır

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
my_array[:2,:2]


array([[1, 2],
       [4, 5]])

In [44]:
my_array[1]=np.array([10,10,10])
#indexle satıra ulaşığ veri değiştirme

In [45]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [46]:
my_array[2]=99

In [47]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [48]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [54]:
my_array=np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_array.reshape(5,2)
#5 satır 2 sütun haline getir

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
np.arange( 1,10.1,4)

array([1., 5., 9.])

In [ ]:
#arange numpyda tek boyutlu array oluşturma

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [63]:
np.ones([2,5,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [65]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
my_array=np.random.random([5,2])

In [67]:
my_array

array([[0.80799892, 0.23476177],
       [0.28061232, 0.40445609],
       [0.58278624, 0.75842444],
       [0.92265768, 0.44317315],
       [0.54423772, 0.61975907]])

In [68]:
np.random.randint(100, size=(5,5))
#100 e kadar olan sayılardan rastgele matix oluşturma

array([[58, 61, 51, 30, 10],
       [83, 26, 78, 42, 85],
       [72, 97, 79, 93, 31],
       [19, 94, 23, 44, 51],
       [96, 88,  6, 19, 83]])

In [70]:
np.linspace(5,10,5)
#1 den 10 a kadar 5 eleman

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [71]:
#any(),all(),full(),concatenate(iki listeyi birbirine eklemek )

In [76]:
array1 =np.arange(0,10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
array1=array1.reshape(2,5)

In [78]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.concatenate([array1,array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
np.concatenate([array1,array1],axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### Statistics

In [84]:
array1 =np.arange(0,10)
array1=array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
array1.sum()
#sum(tüm değerleri toplar)

45

In [86]:
array1.mean()

4.5

In [87]:
array1.std()

2.8722813232690143

In [88]:
array1.var()

8.25

In [89]:
array1.sum(axis=1)
#1.axisteki toplamları ver

array([10, 35])

In [90]:
array1.sum(axis=0)
#tüm satırları toplar

array([ 5,  7,  9, 11, 13])

In [91]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
array2=np.arange(0,10)
array2 =array2.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
array2 +10
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
array2=array2 +10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

### Boolean Arrays

In [97]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [98]:
a[0],a[-1]

(0, 3)

In [99]:
a[[0,-1]]

array([0, 3])

In [100]:
a[[True,False,False,True]]

array([0, 3])

In [101]:
a >= 2

array([False, False,  True,  True])

In [102]:
a[a >= 2]

array([2, 3])

In [103]:
a.mean()

1.5

In [104]:
a[a>a.mean()]

array([2, 3])

In [111]:
a[ ~(a> a.mean())]

array([0, 1])

In [105]:
a[(a == 0) | (a==1)]


array([0, 1])

In [106]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [ ]:
#100 e kadar rastegele tamsayılardan oluşan, 3,3 bir matris oluşturun 
#30'dan büyük olanları boolean yöntemi ile fitreleyin

In [109]:
random_array=np.random.randint(100, size=(3,3))
#100 e kadar olan sayılardan rastgele matix oluşturma
random_array

array([[23, 23, 35],
       [28, 55, 68],
       [62,  1, 75]])

In [110]:
random_array[random_array > 30]


array([35, 55, 68, 62, 75])

In [112]:
boolean_array=random_array>30
boolean_array

array([[False, False,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [114]:
random_array[boolean_array]

array([35, 55, 68, 62, 75])

In [120]:
my_array =np.array([0,1,2,3,4,5,6,7,8,9])
array_1=my_array.reshape(5,2)
array_2=my_array.reshape(2,5)

In [121]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [122]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [123]:
np.dot(array_1,array_2)
#iki matrisin çarpımı

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [124]:
array_2.T
#satırdakileri sütun halina getiriyor.

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [125]:
import sys

In [126]:
sys.getsizeof(10)

28

In [127]:
sys.getsizeof(1000**100)

160

In [128]:
np.dtype(int).itemsize
#8 bit olarak gösterir

8

In [130]:
np.dtype(np.int8).itemsize

1

In [131]:
np.dtype(float).itemsize

8

In [132]:
sys.getsizeof([1,2,3])

88

In [134]:
np.array([1,2,3]).nbytes

24

In [135]:
my_list= list(range(100000))

In [136]:
my_array=np.arange(100000)

In [137]:
%time np.sum(my_array ** 2)

CPU times: user 503 µs, sys: 386 µs, total: 889 µs
Wall time: 444 µs


333328333350000

In [138]:
#python listesi için 
%time sum([number ** 2 for number in my_list])

CPU times: user 7.04 ms, sys: 1.14 ms, total: 8.18 ms
Wall time: 7.8 ms


333328333350000